### PR TITLE
WIP for number entities

### PR DESCRIPTION
**Pull request by dwradcliffe**

### CODE REVIEW

**Comment by jlvaillant** [comment]
David, what is that "p0101" constant string I see on the code?

**Comment by dwradcliffe** [comment]
That's the pump circuit object that controls the speed. For some crazy reason you write to that object but read from the pump object. That's what I was discussing in #12

**Comment by jlvaillant** [comment]
I added a comment in that discussion regarding the 1 to many mapping between a pump and the its different settings. "p0101" is NOT the object controlling the speed of the pump, only the speed of the pump WHEN the associated circuit is ON.

**Comment by dwradcliffe** [comment]
I'll split this PR into 2 so we can add the chlorinator and then keep figuring out the pump speed.

**Comment by jlvaillant** [comment]
Sounds good! Thanks David

**Pull request closed without merging**
